### ISSUE TITLE
Better volume control (client)

### ISSUE THREAD

**Issue by propri** [bjoern-tantau/share-your-music#10]
Depending on the users browsers, the volume control of the player is hard to control precisely.
You often want the music to play in a volume that you can hear, while simultaneously hearing other people talk in voice chat.

It is nearly impossible to set the playback volume to a reasonable level with the builtin browser player, a custom control would be very helpful.

**Comment by bjoern-tantau** [comment]
I added a simple number-field to set the volume. It will also be remembered by the browser.
